apiVersion: apps/v1
kind: Deployment
metadata:
  name: kellner-deployment
  namespace: kellner-rechner
  labels:
    app: kellner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kellner
  template:
    metadata:
      labels:
        app: kellner
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name: kellner-container
        image: ghcr.io/jonashinterdorfer/kellner-rechner/kellner:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "50m"
          requests:
            memory: "256Mi"
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: kellner-service
  namespace: kellner-rechner
spec:
  selector:
    app: kellner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kellner-ingress
  namespace: kellner-rechner
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`kellner.hinterdorfer.dev`)
    services:
    - name: kellner-service
      port: 80
  tls:
    certResolver: le
